In [1]:
import pandas as pd
import sys
import os
from dotenv import load_dotenv

sys.path.append(os.path.abspath('..'))
from helpers import RAND_STATE
from helpers import feature_eng_helpers as fp
from helpers import submission_write as sw

IMPORTING DATA

In [2]:
load_dotenv()
train0 = pd.read_csv(os.getenv("CLEAN_DATA_PATH") + "/" + "sales_train_cnt_0.csv")

In [3]:
submit_ids = pd.read_csv(os.getenv("ORIGINAL_DATA_PATH") + "/" + "test.csv")

In [4]:
train_sub = submit_ids[["shop_id", "item_id"]]
train_sub["month_block_num"] = 34

In [5]:
train_sub.head()

   shop_id  item_id  month_block_num
0        5     5037               34
1        5     5320               34
2        5     5233               34
3        5     5232               34
4        5     5268               34

In [6]:
train_sub2 = fp.add_features_to_sub_df(train_sub, train0)

In [7]:
train_sub2.head()

   shop_id  item_id  month_block_num  item_cnt_month  item_price_median
0        5     5037               34             0.0                0.0
1        5     5320               34             0.0                0.0
2        5     5233               34             1.0             1199.0
3        5     5232               34             0.0                0.0
4        5     5268               34             0.0                0.0

In [9]:
train_sub2.to_csv(os.getenv("SUBMISSION_DATA_PATH") + "/" + "train_submission.csv", index=False)